# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.FileField(upload_to='about/', verbose_name='Upload the featured image')),
                ('bio', models.TextField()),
                ('site', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('statement', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_file', models.FileField(upload_to=portfolio.models.filepath, verbose_name='Upload a file')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Category')),
            ],
        ),
    ]
