# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20161228_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
