# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20161229_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='featured image'),
        ),
    ]
