# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20161229_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='feature image on the home page'),
        ),
        migrations.AlterField(
            model_name='work',
            name='media_file',
            field=models.FileField(upload_to=portfolio.models.filepath, verbose_name='upload a file'),
        ),
        migrations.AlterField(
            model_name='work',
            name='order',
            field=models.IntegerField(default=1, verbose_name='position on the category page'),
        ),
    ]
