# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20170127_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work',
            new_name='Project',
        ),
    ]
