# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20170127_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='media_file',
            new_name='project_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
