# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('alt_text', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_image', models.FileField(upload_to=portfolio.models.filepath, verbose_name='upload a file')),
                ('order', models.IntegerField(default=1, verbose_name='position on the category page')),
                ('featured', models.BooleanField(default=False, verbose_name='feature image on the project page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project')),
            ],
        ),
    ]
