# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('portfolio', '0014_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibitions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_image', models.FileField(upload_to='exhibitions/')),
                ('text', models.TextField()),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name_plural': 'exhibitions page',
            },
        ),
    ]
