# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20170129_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
    ]
