# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20170209_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=1, verbose_name='position on the sidebar'),
        ),
    ]
