# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_work_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='featured',
        ),
    ]
