# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_work_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='work',
            name='large',
            field=models.FileField(blank=True, upload_to=portfolio.models.filepath, verbose_name='upload a large image (optional)'),
        ),
        migrations.AddField(
            model_name='work',
            name='medium',
            field=models.FileField(blank=True, upload_to=portfolio.models.filepath, verbose_name='upload a medium-sized image (optional)'),
        ),
        migrations.AddField(
            model_name='work',
            name='small',
            field=models.FileField(blank=True, upload_to=portfolio.models.filepath, verbose_name='upload a mobile-optimized image (optional)'),
        ),
    ]
